{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "orb-chrysa.fullname" . }}-raft
  namespace: {{ include "orb-chrysa.namespace" . }}
  labels:
    {{- include "orb-chrysa.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "orb-chrysa.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "orb-chrysa.name" . }}
              app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: raft
    - ports:
        - protocol: TCP
          port: registry
{{- end }}
