storage:
  s3:
    endpoint: http://s3.example.internal:9000
    bucket: orb-chrysa

certManager:
  enabled: true
  issuerRef:
    name: orb-chrysa-ca
    kind: ClusterIssuer
    group: cert-manager.io

server:
  tls:
    dnsNames:
      - registry.example.internal
      - orb-chrysa-nodeport.example.internal
